### PR TITLE
Feat/hashtags usertags

### PR DESCRIPTION
**Pull request by Medcell1**
- [x] I have performed a self-review of my code
- [x] I have tested using 2 or more accounts
- [ ] I created tests for necessary files
- [x] I added videos and/or images if this PR changed the routes or app behavior in a way the user would notice

### Description
Hashtags and user-tags are being extracted from Post's caption and stored as a property(array) in the Post Object
Screenshot 2024-08-22 113329

Screenshot 2024-08-22 113834

### CODE REVIEW

**Comment by MikkyBoy357** [comment]
@Medcell1 Please, when you want to create a new branch, always checkout dev branch and git pull before you create a new branch.

**Comment by MikkyBoy357** [comment]
@Medcell1 Also, please exclude the files under /.idea from git and push again

**Comment by Medcell1** [comment]
> @Medcell1 Also, please exclude the files under /.idea from git and push again

Done

**Comment by MikkyBoy357** [comment]
@Medcell1 Leave it.It seems this PR is fucked. Create a new branch from `dev`. Copy paste the code without your .idea folder and send another PR

Screenshot 2024-08-26 at 22 20 37

**Comment by Medcell1** [comment]
Removed, had to remove the directory from the index.

**Pull request merged**
